version: "3.7"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3309:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
  mailcatcher:
    image: schickling/mailcatcher
    expose:
      - "1080"
      - "1025"
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  my-db:
