POST http://localhost:3000/api/links/create
Content-Type: application/json 

{
  "uri": "https://private.youtube.link",
  "price": "9.99"
}

### 

GET  http://localhost:3000/api/links/MZAP3AZS8427pm4LBzJDG

###

GET  http://localhost:3000/api/to/MZAP3AZS8427pm4LBzJDG

### PAYMENTS

@Paypal = https://api-m.sandbox.paypal.com
@PaypalClientId = {{$dotenv NEXT_PUBLIC_PAYPAL_CLIENT_ID}}
@PaypalSecret = {{$dotenv PAYPAL_SECRET}}

@PaypalAccessToken = {{$dotenv PAYPAL_CLIENT_TOKEN}}
### Get token

POST {{Paypal}}/v1/oauth2/token
Accept: application/json
Accept-Language: en_US
Authorization: Basic {{PaypalClientId}}:{{PaypalSecret}}

grant_type=client_credentials

###

POST {{Paypal}}/v2/checkout/orders
Authorization: Bearer {{PaypalAccessToken}}
Content-Type: application/json