POST http://localhost:3000/api/links/create
Content-Type: application/json 

{
  "uri": "https://private.youtube.link",
  "price": "9.99"
}

### 

POST http://localhost:3000/api/links/oembed
Content-Type: application/json

{
  "uri": "https://vimeo.com/689275417"
}

###

GET  http://localhost:3000/api/links/MZAP3AZS8427pm4LBzJDG

###

GET  http://localhost:3000/api/to/MZAP3AZS8427pm4LBzJDG

### PAYMENTS

@Paypal = https://api-m.sandbox.paypal.com
@PaypalClientId = {{$dotenv NEXT_PUBLIC_PAYPAL_CLIENT_ID}}
@PaypalSecret = {{$dotenv PAYPAL_SECRET}}

@PaypalAccessToken = {{$dotenv PAYPAL_CLIENT_TOKEN}}
### Get token

POST {{Paypal}}/v1/oauth2/token
Accept: application/json
Accept-Language: en_US
Authorization: Basic {{PaypalClientId}}:{{PaypalSecret}}

grant_type=client_credentials

###
#57595573V1292361Y

GET {{Paypal}}/v2/checkout/orders/19A966449S213464H
#GET {{Paypal}}/v2/checkout/orders/57595573V1292361Y
Authorization: Bearer {{PaypalAccessToken}}
Content-Type: application/json

### start partner onboarding:
POST {{Paypal}}/v2/customer/partner-referrals
Authorization: Bearer {{PaypalAccessToken}}
Content-Type: application/json

{
    "tracking_id": "foobar",
    "operations": [
      {
        "operation": "API_INTEGRATION",
        "api_integration_preference": {
          "rest_api_integration": {
            "integration_method": "PAYPAL",
            "integration_type": "THIRD_PARTY",
            "third_party_details": {
              "features": [
                "PAYMENT",
                "REFUND"
             ]
            }
          }
        }
      }
    ],
    "products": [
      "EXPRESS_CHECKOUT"
    ],
   "legal_consents": [
      {
        "type": "SHARE_DATA_CONSENT",
        "granted": true
      }
    ]
}

### get partner merchant details
GET https://api-m.sandbox.paypal.com/v1/customer/partners/X4LS5MX6Z2MX2/merchant-integrations/9X4J4F77QWQUU 
Authorization: Bearer {{PaypalAccessToken}}
Content-Type: application/json